### ISSUE TITLE
piano key labels are not getting removed when switching keymaps

### ISSUE THREAD

**Issue by ericrosenbaum** [ericrosenbaum/MK-1#6]
Before adding new labels, the function setPianoLabels() should be removing all the old ones: https://github.com/ericrosenbaum/MK-1/blob/20ae264c13c43983d51d113e1b14bf82724a4f93/sketch.js#L227-232

This worked before I put this project on github, which is when I also updated to CDN versions of the p5 files. I'm guessing this has to do with a change to the p5 DOM addon. 

any ideas @lmccart?

**Comment by lmccart** [comment]
oops, sorry about that! I think the new version should work now. it will take a little bit for it to update on cdnjs. cool project!

**Comment by ericrosenbaum** [comment]
amazing! fixed. thanks!

**Comment by lmccart** [comment]
also, there is a new [keyIsDown()](http://p5js.org/reference/#p5/keyIsDown) function, which may be helpful, if not too late
